pipeline{
    
    agent any
    
    environment{
        FOO = "PIPELINE"
        BUILD_NUM_ENV = currentBuild.getName()
        
    }
    stages{
        stage("local"){
            environment {
                
                BAR = "STAGE"
            }
          steps{
              
              sh 'echo "FOO is $FOO BAR is $BAR"'
          }

        }
      stage("global"){
          
          steps{
              
              sh 'echo "FOO is $FOO BAR is $BAR"'
               
              sh 'echo "BUILD_NUM_ENV is $BUILD_NUM_ENV"'
          }

      }

    }


}
